### ISSUE TITLE
libyang and frr: bump ebuilds, recommended versions and todo

### ISSUE THREAD

**Issue by rzalamena** [FRRouting/gentoo-overlay#55]
Summary
------------

FRR and known good libyang versions:

FRR version     | libyang version
--------------------|--------------------
7.0 or less        | 0.16-r3
7.1                    | 0.16-r3
7.2                    | 0.16-r3
7.3                    | 0.16-r3
7.4                    | 0.16-r3 (maybe 1.0.167)
\>7.4                  | 1.0.167

TODOs
---------

- [x] Use `libyang` 0.16-r3 in FRR 7.3 or lesser by default (I've run into some problems using newer versions).
- [x] Bump `libyang` ebuild to 1.0.167 (from 1.0.109).
- [x] ~Test new `libyang` 1.0.167 in FRR 7.4 before defaulting it there.~ (7.4 will use 0.16-r3 still)
- [x] FRR `master` will soon default to `libyang` 1.0.167 and will no longer use 0.16-r3 ( see frrouting/frr#6376 )
- [x] Write FRR ebuilds that use `watchfrr` instead of routing daemons in init scripts/systemd
- [x] Add ebuild for FRR 7.3.1
- [x] Add ebuilds for FRR 7.4.
- [x] Implement OpenRC reload with `frr-reload.py`.

If anyone feels like doing any of the activities above, please let me know. I'll slowly work on these as I find time.
